# Load libraries
library(dplyr)
library(Seurat)
library(patchwork)
library(limma)
library(xlsx)
library(readxl)

# Load .RData image

# Keep the top 12 markers for each cluster
cluster0Top12Markers = head(cluster0Markers, 12)
cluster1Top12Markers = head(cluster1Markers, 12)
cluster2Top12Markers = head(cluster2Markers, 12)
cluster3Top12Markers = head(cluster3Markers, 12)
cluster4Top12Markers = head(cluster4Markers, 12)
cluster5Top12Markers = head(cluster5Markers, 12)
cluster6Top12Markers = head(cluster6Markers, 12)
cluster7Top12Markers = head(cluster7Markers, 12)
cluster8Top12Markers = head(cluster8Markers, 12)
cluster9Top12Markers = head(cluster9Markers, 12)
cluster10Top12Markers = head(cluster10Markers, 12)
# cluster11Top12Markers = head(cluster11Markers, 12)
# cluster12Top12Markers = head(cluster12Markers, 12)
# cluster13Top12Markers = head(cluster13Markers, 12)
# cluster14Top12Markers = head(cluster14Markers, 12)
# cluster15Top12Markers = head(cluster15Markers, 12)
# cluster16Top12Markers = head(cluster16Markers, 12)
# cluster17Top12Markers = head(cluster17Markers, 12)
# cluster18Top12Markers = head(cluster18Markers, 12)
# cluster19Top12Markers = head(cluster19Markers, 12)
# cluster20Top12Markers = head(cluster20Markers, 12)

# .pdf export of Feature & Violin Plots
pdf(file = sprintf("%s_Top 12 Markers.pdf", filePrefix))
FeaturePlot(data, features =  cluster0Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster0Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster1Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster1Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster2Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster2Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster3Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster3Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster4Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster4Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster5Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster5Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster6Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster6Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster7Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster7Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster8Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster8Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster9Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster9Top12Markers$PeaxiGene, label = TRUE)
FeaturePlot(data, features =  cluster10Top12Markers$PeaxiGene, label = TRUE)
VlnPlot(data, features =  cluster10Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster11Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster11Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster12Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster12Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster13Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster13Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster14Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster14Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster15Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster15Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster16Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster16Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster17Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster17Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster18Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster18Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster19Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster19Top12Markers$PeaxiGene, label = TRUE)
# FeaturePlot(data, features =  cluster20Top12Markers$PeaxiGene, label = TRUE)
# VlnPlot(data, features =  cluster20Top12Markers$PeaxiGene, label = TRUE)
dev.off()
